### ISSUE TITLE
using option object's 'initMode'

### ISSUE THREAD

**Issue by alibinjalal** [benknight/kuler-d3#4]
var colorwheel = new ColorWheel({
				initMode: 'Analogous'
			});
			colorwheel.bindData(5);

error:
Uncaught ReferenceError: modes is not defined
colorwheel.js:465

**Comment by benknight** [comment]
Hey @alibinjalal, sorry about that, the master branch isn't in a stable state.  I would recommend switching over to the gh-pages branch and follow that example.  I will update master as soon as I can!  Let me know if you need any extra help setting it up.

**Comment by alibinjalal** [comment]
thanks
