### ISSUE TITLE
Project License?

### ISSUE THREAD

**Issue by anthkris** [benknight/kuler-d3#5]
Howdy Ben,

I'm working with a university on a MOOC about the fundamentals of programming and, more specifically, currently on a module on game and mobile design. One of the things we'll cover briefly (very briefly) is color theory as it applies to game and mobile design. I saw your interactive, which seems like a perfect fit to allow students to experiment with various basic color theory principles. I wanted to know, might we fork the project and embed it in the course? 

The course is free, though participants can pay to receive a verified certificate.

Let me know if this is possible.

**Comment by benknight** [comment]
Sorry for the delay here, but I finally added a LICENSE file with the basic MIT license.

Did you end up using the code anyway?  I'd love to hear about how it went.

**Comment by anthkris** [comment]
Thanks @benknight! We're just at the point where we're adding stuff in to the course in preparation for release. I linked to it but didn't embed it. I'll be sure to let you know when we get any comments!
